---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
      - cce295526e01b62ae2806f9b4d245744 #Ignore duplication of a block of require() statements in build/makeDocs and providers/nodebb/index
  eslint:
    enabled: false # Temporary disable due to current nonsupport of eslint2.x
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/**
- docs/**