language: node_js
node_js:
  - node
  - iojs
  - '0.12'
  - 'iojs-v2.0'
  - 'iojs-v2.1'
before_script:
  - rm -rf ./coverage
  - npm run gulp preBuild
  - git log|egrep '^commit' -c
after_script:
  - npm run gulp postBuild
  - test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
    - es6-dev