language: node_js
node_js:
- node
- iojs
- '0.12'
- '4.1'
- '4.2'
- '5.5'
- '5.6'
before_script:
- rm -rf ./coverage
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com" > .git/credentials
script:
- npm run lint
- npm test
after_script:
- [[ "$TRAVIS_JOB_NUMBER" == *.1 ]] && npm run buildDocs && npm run pushDocs
- test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/.bin/coveralls
- test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/.bin/codeclimate-test-reporter 
branches:
  only:
  - master
  - integration
notifications:
  slack:
    secure: Fycz8f/0HY/rgiMePSF4IhavbvSR0/B20gGX4sHHd83ql6WLOx8bf+Al348HhF8GobqD3uTUs1tQPmIGGHdPZ2l+0ZFythSSUNy766612WfyYOpCAqXeCALgcciKzrw7lkECtOLgBOm7vRWVSOfxHXle2NefZR3Q8eNPWpKlNP8=
addons:
    code_climate:
        repo_token: ae8ad61d2992922c37dd7f4aec7fcd56d516ff6f75f1bfde75e4762f06660b69